### ISSUE TITLE
Including a Grammar file for the language server

### ISSUE THREAD

**Issue by SharkJ** [mickaelistria/eclipse-languageserver-demo#6]
I was going through your directories and was wondering where you have included a grammar file for your language server. I have a grammar file generated using Antlr4 and I want to implement a language server from it. Could you kindly help me by telling how to include my grammar file in this directory?

**Comment by mickaelistria** [comment]
In this repository, we've used a standalone black-box language server. Whether it uses antlr or not is not known to the client side.
I'm not aware of a language server that an be configured/generated from an Antlr grammar. It would be more something to suggest as a new feature/subproject to.Antlr. Then once such LS exists, it's possible to mimic what's done in this repo to connect the LS to the Eclipse IDE.
The only grammar we have here is the Textmate grammar, which is only used for syntax highlighting. Not sure it's related.
HTH

**Comment by SharkJ** [comment]
Thanks for the reply. Could you kindly tell me where in the repo can I find the Textmate grammar? I apologize if the question seems silly, but I'm very new to this.

**Comment by mickaelistria** [comment]
https://github.com/textmate/antlr.tmbundle/blob/master/Syntaxes/ANTLR.plist is probably what you want.

**Comment by SharkJ** [comment]
@mickaelistria Thank You so much! 👍
